### ISSUE TITLE
pod shifting on neurohackademy

### ISSUE THREAD

**Issue by satra** [neurohackademy/nh2020-jupyterhub#118]
@consideRatio - in this line: https://github.com/neurohackademy/nh2020-jupyterhub/blob/8bc0d8304d5090d3a1e21a038a68f0a940e31809/deployments/hub-neurohackademy-org/config/prod.yaml#L72

i can see that many users could be admitted into a single node. what happens when the user starts requesting more compute resources? on gcp does the pod get moved easily to other nodes? also the memory guarantee is 16GB, which i am assuming will also limit the number of users that can get on a node.

**Comment by consideRatio** [comment]
Hi @satra! Let's consider the k8s resource requests made by the pod from the user's actual usage when controlling a container within the pod.

## k8s Pods' resource requests
These influence the k8s based scheduling and eviction of pods.

A k8s pod can request a guarantee, which ensure the pod always have access to the resource no matter what without needing to evict any other pods etc. This means that memory needs to be reserved specifically for the pod if guaranteed, while CPU can be made available for other pods even if a pods have been guaranteed it. By a guarantee of CPU, you are guaranteed a CPU share every 100ms representing your guarantee, but if you don't use your share, others can use it.

## Actual resource consumption by the pods
If a pod is guaranteed 1GB of memory but limited to 4GB of memory, and there are many pods on the same node fitted onto a node, we may run into evictions. If the node has for example 10 pods on it and 16GB of memory, then pods that surpassed their guarantee can start getting evicted, and those that surpassed it by the most are likely the ones to become evicted.

If a user in our JupyterHub wants more resources, then it needs to restart the pod with higher requests, but if the user in the same session needs even more memory or CPU without a restart, its not possible in k8s.

## About our nodes for neurohackademy
We used extremely powerful nodes on neurohackademy, m1-ultramem-40 - they had 40 CPUs and 961 GB of memory, but the GKE managed k8s has a upper limit of 110 user for all nodes, so we ensures also to make use of the resources before we ran into such constraints. On AWS, those limits are far lower, for example 28 pods or similar, but it depends on the node size.

**Comment by satra** [comment]
@consideRatio  - thanks for the detailed explanation. the powerful node makes sense, but what if nodes are not that powerful, but highly scalable (but takes time to start). are there any recommendations in that scenario?

>  If the node has for example 10 pods on it and 16GB of memory, then pods that surpassed their guarantee can start getting evicted, and those that surpassed it by the most are likely the ones to become evicted.

i'm surprised by this scenario. in this setup, they simply won't get an OOM error (as would happen with linux cgroups setup), but get evicted?

also if we take the scenario that there are 10 pods on a node with 10GB with the 1GB guarantee (4GB limit) and all are using 0.1GB. Now two of the pods go up to 4GB use. A third pod now requests 3GB in an operation, what does it look like to an end user?

**Comment by consideRatio** [comment]
Ah, hmmm, good question, not sure. I think kubelet running on the node observes a memory preassure and will try resolve it, but will it go straight to eviction of pods? I actually think the 4GB pod will get evicted rather than the 3GB pod.

The 4GB pod will get OOM exceptions for its processes if it was going beyond its limit of 4GB though.

---

I figure there are two levels of constraints, the containers limit, and the nodes limit. Node limits are enforced by evictions i think, while container limits are enforced in the container scope and sending OOM process terminations i think.

Perhaps node constraints can cause in-pod process terminations as well, im not sure.

---

I recall there was docs added in z2jh by yuvi panda/chris holdgraf about suggested guarantee/limit ratios btw.

**Comment by satra** [comment]
thanks @consideRatio - this is where i am trying to re-balance my understanding of traditional hpc (e.g. slurm) with k8s with jh.

> here was docs added in z2jh by yuvi panda/chris holdgraf about suggested guarantee/limit ratios btw.

i haven't seen a section on this, but if you have a pointer that would be great. 

i'll close this  for now. but i'm very thankful for your explanations.

**Comment by consideRatio** [comment]
Haha yeah i also failed to find it when scanning for it :) I looked and failed to find it myself first, but here is it: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1897! Cheers
