### ISSUE TITLE
Simulate traffic with yuvipanda/hubtraf project

### ISSUE THREAD

**Issue by consideRatio** [neurohackademy/nh2020-jupyterhub#29]
From a slack message to @arokem:

> I'll do some debugging beforehand by scaling up with simulated traffic

I'll try using @yuvipanda's hubtraf project which is [documented here](https://github.com/yuvipanda/hubtraf/blob/master/docs/index.rst).

**Comment by yuvipanda** [comment]
Great, @consideRatio. I'd recommend using the python version directly, without using helm. Running from a VM would also help massively in taking the stability of your own internet connection out of the equation.

**Comment by consideRatio** [comment]
# Summary

### Short summary

I'll look into why our metrics collector prometheus crashed, but otherwise I feel good about the results of this simulation.

### Hubtraf startup command

I ran hubtraf like this:

```shell
# Simulate 975 users arriving over 15 minutes time
hubtraf-simulate https://hub.neurohackademy.org 975 \
  --user-prefix=hubtraf \
  --user-session-min-runtime=900 \
  --user-session-max-runtime=900 \
  --user-session-max-start-delay=900 \
  --json
```

### Helm chart adjustments for hubtraf

I configured the Helm chart for stress test with hubtraf like described in this file.

https://github.com/neurohackademy/nh2020-jupyterhub/blob/master/hubtraf-chart-values.yaml

### The CI system aborted the simulation

I created around 500 users before the CI system was triggered by #40 being merged, which updated the deployment back to normal use and aborted the experiment. I felt I got sufficient information about the stability though so I didn't re-run it.

### Hubtraf errors I didn't understand

I experienced some errors in `hubtraf`, I'm confused why they show up after 300 seconds specifically. Why not the 900 seconds I configured in my Helm chart under singleuser.startTimeout?

```
Failure: server-start hubtraf-835 phase:failed duration:324.47752402100014 reason:timeout
```

### Transient NFS mounting issues

I had been worried about getting stubborn issues with pods failing to mount the NFS volume, and I got some, but they were transient and went away. Here is one example of such issue. I've considered ideas like mounting the NFS folder once per node onto a hostPath or similar, and then exposing that to the user containers. I'm not sure if that is viable, but I figure it seems we don't need to do something like that since the issues were transient.

```
  Type     Reason             Age                     From                                        Message
  ----     ------             ----                    ----                                        -------
  Normal   NotTriggerScaleUp  6m45s                   cluster-autoscaler                          pod didn't trigger scale-up (it wouldn't fit if a new node is added):
  Warning  FailedScheduling   6m39s (x18 over 6m47s)  hub-neurohackademy-org-prod-user-scheduler  0/13 nodes are available: 1 node(s) didn't match node selector, 1 node(s) had taints that the pod didn't tolerate, 11 Insufficient memory.
  Normal   Scheduled          6m38s                   hub-neurohackademy-org-prod-user-scheduler  Successfully assigned default/jupyter-hubtraf-2d544 to gke-nh-2020-user-a48453f5-7dr3
  Warning  FailedMount        6m32s                   kubelet, gke-nh-2020-user-a48453f5-7dr3     MountVolume.SetUp failed for volume "nfs-pv" : mount failed: exit status 1
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/8ccca603-75f0-4a47-b78a-589552c2db54/volumes/kubernetes.io~nfs/nfs-pv --scope -- /home/kubernetes/containerized_mounter/mounter mount -t nfs 10.60.0.18:/nh /var/lib/kubelet/pods/8ccca603-75f0-4a47-b78a-589552c2db54/volumes/kubernetes.io~nfs/nfs-pv
Output: Running scope as unit: run-r51f206ea24e94b87a880fc1ae2277c66.scope
Mount failed: mount issued for NFS V3 but unable to run rpcbind:
 Output: rpcbind: another rpcbind is already running. Aborting

 Error: exit status 1
  Normal  SuccessfulAttachVolume  6m32s  attachdetach-controller                  AttachVolume.Attach succeeded for volume "pvc-a1de68d7-962e-4f30-8b4c-9fd1db9a2247"
  Normal  Pulling                 6m13s  kubelet, gke-nh-2020-user-a48453f5-7dr3  Pulling image "busybox"
  Normal  Pulled                  53s    kubelet, gke-nh-2020-user-a48453f5-7dr3  Successfully pulled image "busybox"
  Normal  Pulling                 37s    kubelet, gke-nh-2020-user-a48453f5-7dr3  Pulling image "jupyterhub/k8s-network-tools:0.9.0-n000.h5fd3f0d"
  Normal  Created                 37s    kubelet, gke-nh-2020-user-a48453f5-7dr3  Created container chown-nfs-mount-to-jovyan
  Normal  Started                 37s    kubelet, gke-nh-2020-user-a48453f5-7dr3  Started container chown-nfs-mount-to-jovyan
  Normal  Pulled                  32s    kubelet, gke-nh-2020-user-a48453f5-7dr3  Successfully pulled image "jupyterhub/k8s-network-tools:0.9.0-n000.h5fd3f0d"
  Normal  Created                 32s    kubelet, gke-nh-2020-user-a48453f5-7dr3  Created container block-cloud-metadata
  Normal  Started                 32s    kubelet, gke-nh-2020-user-a48453f5-7dr3  Started container block-cloud-metadata
  Normal  Pulled                  31s    kubelet, gke-nh-2020-user-a48453f5-7dr3  Container image "us.gcr.io/neurohackademy/nh-2020-env:7cd42da" already present on machine
  Normal  Created                 30s    kubelet, gke-nh-2020-user-a48453f5-7dr3  Created container notebook
  Normal  Started                 30s    kubelet, gke-nh-2020-user-a48453f5-7dr3  Started container notebook
```

All in all, the nodes were added and then removed, I don't think any user had to wait more than ~6-7 minutes to get started with a user arriving on average every second for 15 minutes.

### Prometheus crashed
Our single prometheus pod crashed when we had that many pods running, I didn't see any error in the logs though. `kube-state-metrics` and `kube-node-exporter` pods worked fine though. I'll inspect the mybinder.org-deploy repo's configuration of resources for the prometheus-server pods.

**Comment by yuvipanda** [comment]
Thanks for the detailed writeup, @consideRatio!

The 300s is hardcoded [here](https://github.com/yuvipanda/hubtraf/blob/master/hubtraf/user.py#L137). The 900 you mention is for the full hubtraf run, not for the user start timeout. We should make that configurable.

re: NFS & hostPath, that's what we did at berkeley for a long time - see https://github.com/berkeley-dsep-infra/datahub/pull/1577 for the daemonset and https://github.com/yuvipanda/k8s-nfs-mounter for the source code. I don't think it's worth it, we moved away from it a few weeks ago.

Hope this is useful!

**Comment by consideRatio** [comment]
@yuvipanda its very useful, your experience and tooling is guiding the way as usual! Thank you so much for giving input on this! :heart: :tada:

**Comment by consideRatio** [comment]
I also did additional testing in #44
