### ISSUE TITLE
Allow participants in at Wednesday July 22

### ISSUE THREAD

**Issue by consideRatio** [neurohackademy/nh2020-jupyterhub#30]
As discussed with @arokem we'll try letting users into the JupyterHub deployment July 21 / July 22. I'll plan that more specifically now to the morning of July 22 in the PT timezone of Seattle.

@arokem, at that point in time, I figure I'll add everyone with a unique and verified GitHub account in the participant list (cell N31) to the ACL. Does this sound alright to you? I can pass this in encrypted or decrypted without trouble - any preference on that?

**Comment by arokem** [comment]
Yes. That sounds right. I will alert everyone and contact the others on Monday, to make sure that I get the GitHub user names for as many as possible.

**Comment by consideRatio** [comment]
Closed by #48
