### ISSUE TITLE
Install JupyterLab introduction plugin

### ISSUE THREAD

**Issue by consideRatio** [neurohackademy/nh2020-jupyterhub#32]
As I presume there will be people joining the course new to Jupyter and JupyterLab, this could be useful: https://github.com/fcollonval/jupyterlab-tour

**Comment by arokem** [comment]
Oh yes! I didn't know about this. Would be awesome to include.

Do you think this should be instead of the welcome notebook I had in https://github.com/neurohackademy/nh2020-curriculum/pull/1?

**Comment by consideRatio** [comment]
@arokem I think we will benefit from having both as the jupyterlab-tour extension alongside an readme file from us as that can contain more in depth content such as those videos and possibly something custom.

I'll experiment with this and report back - I've not tested it yet!

**Comment by consideRatio** [comment]
@arokem the JupyterLab Tour plugin is installed and I think it is great! I wrote more about customizing the workspace for JupyterLab on first startup in https://github.com/neurohackademy/nh2020-jupyterhub/issues/27#issuecomment-660580594.

Although, I think a new user really should watch the first video you linked no matter what to learn about the concept of cells etc.
