### ISSUE TITLE
Additional stress testing with hubtraf

### ISSUE THREAD

**Issue by consideRatio** [neurohackademy/nh2020-jupyterhub#44]
## Setup before test

I increased the resource requests on the hub/autohttps/proxy/prometheus pods to be more like mybinder.org-deploy. I also made the hub pod and prometheus pods get to use a SSD disk. Then I increased the speed users logged in to ~2/second.

```
hubtraf-simulate https://hub.neurohackademy.org 500 \
  --user-prefix=hubtraf \
  --user-session-min-runtime=280 \
  --user-session-max-runtime=300 \
  --user-session-max-start-delay=240 \
  --json
```

I conclude that the hub pod works at full speed, but caps at 1 CPU. I wonder if this relates to the issue documented with Mybinder.org during SciPy recently: https://github.com/jupyterhub/mybinder.org-deploy/pull/1524/files.

![image](https://user-images.githubusercontent.com/3837114/88015964-b38e5e80-cb22-11ea-8c6f-03cac6289a30.png)

## Hub overloaded

It seems like JupyterHub overloads after a while of having a significant user base at the same time it tries to manage ~2 logins every second. Here is an example where we can see a pattern in the response times peaks. It goes to 5-7 seconds from being at 0-2 seconds.

```
Success: server-start hubtraf-161 phase:complete attempt:6 duration:78.21370672000921
Success: kernel-start hubtraf-216 duration:0.4907634159899317
Success: kernel-start hubtraf-161 duration:0.49913186200137716
Success: login hubtraf-377 duration:0.5450534709962085
Success: login hubtraf-245 duration:0.5802390059980098
Success: login hubtraf-427 duration:2.1807031169882976
Success: login hubtraf-95 duration:5.5254654309974285
Success: login hubtraf-399 duration:5.887370619006106
{"username": "hubtraf-262", "action": "login", "phase": "failed", "duration": 37.35689921499579, "event": "Login: Failed with response <ClientResponse(https://hub.neurohackademy.org/hub/login) [503 Service Unavailable]>\n<CIMultiDictProxy('Content-Type': 'text/html', 'Date': 'Tue, 21 Jul 2020 05:18:17 GMT', 'Strict-Transport-Security': 'max-age=15724800', 'Transfer-Encoding': 'chunked')>\n", "timestamp": "2020-07-21T05:18:17.952211Z"}
{"username": "hubtraf-176", "action": "login", "phase": "failed", "duration": 37.36891293099325, "event": "Login: Failed with response <ClientResponse(https://hub.neurohackademy.org/hub/login) [503 Service Unavailable]>\n<CIMultiDictProxy('Content-Type': 'text/html', 'Date': 'Tue, 21 Jul 2020 05:18:17 GMT', 'Strict-Transport-Security': 'max-age=15724800', 'Transfer-Encoding': 'chunked')>\n", "timestamp": "2020-07-21T05:18:17.960500Z"}
{"username": "hubtraf-204", "action": "login", "phase": "failed", "duration": 37.38491577201057, "event": "Login: Failed with response <ClientResponse(https://hub.neurohackademy.org/hub/login) [503 Service Unavailable]>\n<CIMultiDictProxy('Content-Type': 'text/html', 'Date': 'Tue, 21 Jul 2020 05:18:17 GMT', 'Strict-Transport-Security': 'max-age=15724800', 'Transfer-Encoding': 'chunked')>\n", "timestamp": "2020-07-21T05:18:17.978307Z"}
{"username": "hubtraf-487", "action": "login", "phase": "failed", "duration": 37.39666890499939, "event": "Login: Failed with response <ClientResponse(https://hub.neurohackademy.org/hub/login) [503 Service Unavailable]>\n<CIMultiDictProxy('Content-Type': 'text/html', 'Date': 'Tue, 21 Jul 2020 05:18:17 GMT', 'Strict-Transport-Security': 'max-age=15724800', 'Transfer-Encoding': 'chunked')>\n", "timestamp": "2020-07-21T05:18:17.993914Z"}
{"username": "hubtraf-329", "action": "login", "phase": "failed", "duration": 37.794268840996665, "event": "Login: Failed with response <ClientResponse(https://hub.neurohackademy.org/hub/login) [503 Service Unavailable]>\n<CIMultiDictProxy('Content-Type': 'text/html', 'Date': 'Tue, 21 Jul 2020 05:18:19 GMT', 'Strict-Transport-Security': 'max-age=15724800', 'Transfer-Encoding': 'chunked')>\n", "timestamp": "2020-07-21T05:18:19.410594Z"}
Success: login hubtraf-391 duration:7.233230842000921
Success: login hubtraf-144 duration:7.267246450006496
Success: login hubtraf-258 duration:6.2956970109953545
Success: login hubtraf-172 duration:6.328638210994541
{"username": "hubtraf-470", "action": "login", "phase": "failed", "duration": 38.2977595669945, "event": "Login: Failed with response <ClientResponse(https://hub.neurohackademy.org/hub/login) [503 Service Unavailable]>\n<CIMultiDictProxy('Content-Type': 'text/html', 'Date': 'Tue, 21 Jul 2020 05:18:19 GMT', 'Strict-Transport-Security': 'max-age=15724800', 'Transfer-Encoding': 'chunked')>\n", "timestamp": "2020-07-21T05:18:19.927816Z"}
{"username": "hubtraf-268", "action": "login", "phase": "failed", "duration": 38.32013315799122, "event": "Login: Failed with response <ClientResponse(https://hub.neurohackademy.org/hub/login) [503 Service Unavailable]>\n<CIMultiDictProxy('Content-Type': 'text/html', 'Date': 'Tue, 21 Jul 2020 05:18:19 GMT', 'Strict-Transport-Security': 'max-age=15724800', 'Transfer-Encoding': 'chunked')>\n", "timestamp": "2020-07-21T05:18:19.935039Z"}
{"username": "hubtraf-31", "action": "login", "phase": "failed", "duration": 38.330350952004665, "event": "Login: Failed with response <ClientResponse(https://hub.neurohackademy.org/hub/login) [503 Service Unavailable]>\n<CIMultiDictProxy('Content-Type': 'text/html', 'Date': 'Tue, 21 Jul 2020 05:18:19 GMT', 'Strict-Transport-Security': 'max-age=15724800', 'Transfer-Encoding': 'chunked')>\n", "timestamp": "2020-07-21T05:18:19.938255Z"}
{"username": "hubtraf-375", "action": "login", "phase": "failed", "duration": 37.3831967030128, "event": "Login: Failed with response <ClientResponse(https://hub.neurohackademy.org/hub/login) [503 Service Unavailable]>\n<CIMultiDictProxy('Content-Type': 'text/html', 'Date': 'Tue, 21 Jul 2020 05:18:19 GMT', 'Strict-Transport-Security': 'max-age=15724800', 'Transfer-Encoding': 'chunked')>\n", "timestamp": "2020-07-21T05:18:19.978961Z"}
Success: login hubtraf-443 duration:6.782176831999095
Success: login hubtraf-402 duration:5.823431127995718
Success: login hubtraf-379 duration:4.85200224199798
Success: login hubtraf-367 duration:4.8867618840013165
Success: login hubtraf-461 duration:4.9100733939994825
Success: login hubtraf-477 duration:3.937473357989802
Success: login hubtraf-60 duration:3.9768976920022396
Success: login hubtraf-182 duration:0.7963079740002286
Success: login hubtraf-277 duration:0.8260122210049303
Success: login hubtraf-94 duration:1.5295185550057795
Success: login hubtraf-296 duration:1.5603235220041825
Success: login hubtraf-1 duration:2.546236879003118
Success: login hubtraf-130 duration:2.5765418770024553
Success: login hubtraf-72 duration:2.607647294003982
Success: login hubtraf-319 duration:2.636863061998156
```

### Typical crash

For me, hubtraf itself typically crashes after a while of hard testing

```
Failure: kernel-stop hubtraf-32 exception:<ClientResponse(https://hub.neurohackademy.org/user/hubtraf-32/api/kernels/339cf55c-85c8-481a-81d3-00a414164acd) [403 Forbidden]>
<CIMultiDictProxy('Content-Length': '40', 'Content-Security-Policy': "frame-ancestors 'self';report-uri /hub/security/csp-report; default-src 'none'", 'Content-Type': 'application/json', 'Date': 'Tue, 21 Jul 2020 05:23:33 GMT', 'Server': 'TornadoServer/6.0.3', 'Strict-Transport-Security': 'max-age=15724800', 'X-Content-Type-Options': 'nosniff', 'X-Jupyterhub-Version': '1.1.0')>
 duration:0.49191117999725975
Traceback (most recent call last):
  File "/home/erik/miniforge3/bin/hubtraf-simulate", line 11, in <module>
    load_entry_point('hubtraf', 'console_scripts', 'hubtraf-simulate')()
  File "/home/erik/dev/contrib/yuvipanda/hubtraf/hubtraf/simulate.py", line 98, in main
    loop.run_until_complete(run(args))
  File "/home/erik/miniforge3/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/home/erik/dev/contrib/yuvipanda/hubtraf/hubtraf/simulate.py", line 44, in run
    outputs = await asyncio.gather(*awaits)
  File "/home/erik/dev/contrib/yuvipanda/hubtraf/hubtraf/simulate.py", line 29, in simulate_user
    await u.stop_server()
  File "/home/erik/dev/contrib/yuvipanda/hubtraf/hubtraf/user.py", line 173, in stop_server
    assert self.state == User.States.SERVER_STARTED
AssertionError
```

HubTraf crashed for me at this point in time:

![image](https://user-images.githubusercontent.com/3837114/88016424-a7ef6780-cb23-11ea-9ac9-a7207545e200.png)

### Configurable logging

I manually updated the code of hubtraf to avoid printing debug statements.

## Deletion of pvc/pv's

I cleanup a lot of PVs following my stress tests with `kubectl delete pod,pvc -l hubtraf=delete-me`. That made me end up with the a rate limit by GCP on adding/deleting PVs which is done by creating by PVCs in k8s. Thankfully this automatically resolves over time and they are deleted.

```
status:
  message: 'googleapi: Error 403: Quota exceeded for quota group ''ReadGroup'' and
    limit ''Read requests per 100 seconds'' of service ''compute.googleapis.com''
    for consumer ''project_number:880782900008''., rateLimitExceeded'
  phase: Failed
```

**Comment by consideRatio** [comment]
## Softer stress test

I wanted to see if I could avoid some issues caused by a too fast hub, so I lowered the speed of users logging in to ~1/second.

```
hubtraf-simulate https://hub.neurohackademy.org 500 \
  --user-prefix=hubtraf \
  --user-session-min-runtime=500 \
  --user-session-max-runtime=600 \
  --user-session-max-start-delay=500 \
  --json
```

![image](https://user-images.githubusercontent.com/3837114/88018158-6791e880-cb27-11ea-920c-24514875b2e3.png)

I conclude that this was still too much for the hub. I wonder if a local ssd attached to the node would improve the situation. I figure it relates a lot to making changes etc to the database. I'm really just guessing though.

**Comment by consideRatio** [comment]
## Conclusion

We need to avoid the situation where we get a new user every second starting up a pod, that is about what we can manage with the current JupyterHub implementation it seems. @arokem this is relevant to think of, perhaps you can help avoid that everyone login at the same time?

As an example, I imagine that people may join a video chat ahead of time, if they do, they should probably be greeted with "please start your server at hub.neurohackademy.org" or similar. That way, if an instructor writes "now its time to code!" it doesn't mean everybody starts their server at the same time.

**Comment by consideRatio** [comment]
## Open questions
- Will performance improve by using a external database?
- Will performance improve by using `sqlite-memory` kind of database compared to the `sqlite-pvc` configuration we now use? Is the memory implementation using RAM or is it just not persistent memory of the same kind?

**Comment by consideRatio** [comment]
This relates to https://github.com/jupyterhub/kubespawner/issues/419, perhaps we could configure c.JupyterHub.concurrent_spawn_limit from the z2jh default of 64 to something higher.

**Comment by yuvipanda** [comment]
I was able to easily get 1 user/s going, with the resources specified in https://github.com/2i2c-org/jupyterhub-utoronto/pull/13. The important trick here is to kill the custom user scheduler - it is *much* much slower than the built in GKE scheduler. So pods take longer to start, meaning kubespawner is doing more waiting, meaning everything is slow. Try turning custom user scheduler off and see?

**Comment by consideRatio** [comment]
@yuvipanda oh wow, is the user-scheduler leaving pods that could be scheduled unscheduled, and that cause too significant delays? That was news to me!

When you are testing 1 user/s for example, how many users are you trying with, and are you allocating PVCs and/or mounting NFS storage for them? The first ~100 users always worked fine to spawn when I did this test, the issues comes a while after. Perhaps this also relates to the amount of user-placeholder pods i had. Hmmm.

**Comment by yuvipanda** [comment]
hub also maxes out at 1CPU since python is single threaded.

**Comment by yuvipanda** [comment]
@consideRatio I've a radical idea to use https://github.com/clux/kube-rs as the backing for the kubernetes API calls in kubespawner, which should unlock massive performance gains (hopefully). Someday...

**Comment by consideRatio** [comment]
I should follow up this with usage of `pyspy` to start JupyterHub while doing a hubtraf test, so I can spot what it spend time on.
