### ISSUE TITLE
Is it possible to use submodules for the lecture tutorials?

### ISSUE THREAD

**Issue by noahbenson** [neurohackademy/nh2020-jupyterhub#53]
It would be handy if we could have our own repos for the lectures then add them as sub-modules to the curriculum. This would require a `git submodule init` command after cloning and `git submodule update` after any pull I think.

I've never used `gitpuller`([here in the repo](https://github.com/neurohackademy/nh2020-jupyterhub/blob/1d265a5fbbe45d59a0cda6047007ad1340a98f4a/chart/files/etc/singleuser/k8s-lifecycle-hook-post-start.sh#L11)), and possibly it supports this?

**Comment by arokem** [comment]
Just trying ti understand: what issue does this address? I am happy to give
anyone commit rights into this repo, in case that’s the issue.

**Comment by noahbenson** [comment]
Ah, so I would like to have my own noahbenson/nh2020 repo which is then a submodule in the curriculum repo (instead of adding the files into the curriculum repo directly). Honestly this isn't a big-enough deal to spend any effort on, I'm mostly wondering if `gitpuller` already supports submodules or can be made to support sumodules with a switch (i.e., is this easy?)

**Comment by arokem** [comment]
I suspect it will add complexity. I also like being able to point
participants to one repo they can clone without having to explain sub
modules (honestly, I always mess those up myself).

**Comment by arokem** [comment]
Not that they’ll need to clone anything into the hub, but so they can get
the materials again after the fact.
