### ISSUE TITLE
Intermittent DNS issues for hub.neurohackademy.org

### ISSUE THREAD

**Issue by consideRatio** [neurohackademy/nh2020-jupyterhub#94]
@arokem multiple users reported issues with resolving hub.neurohackademy.org to an IP, and I could reproduce it from my computer by running `nslookup hub.neurohackademy.org`, also when I specified `nslookup hub.neurohackademy.org 8.8.8.8` and `nslookup hub.neurohackademy.org 1.1.1.1` which are common big nameservers.

After an hour or so, the bigger nameservers like 1.1.1.1 and 8.8.8.8 had successfully a pointer to the IP `34.75.11.207`.

What DNS provider is used? I doubt it was overloaded by lookups, but perhaps some cheap provider would throttle lookups and cause issues for us.

**Comment by arokem** [comment]
It's on [dreamhost](https://www.dreamhost.com/). Should we use the bare GCP IP instead?

**Comment by consideRatio** [comment]
We must have a domain name to have HTTPS, so some DNS server need to resolve hub.neurohackademy.org to the IP we have (`34.75.11.207`). I don't know why the DNS lookup failed, but I'd guess it was because of the authoritative DNS server for hub.neurohackademy.org was down for a while.

I think issues can be avoided with a DNS server being down by configuring the lifetime the DNS record is allowed to be cached. If that is only at 300 seconds currently it could be raised significantly for example. We could make it point to another name server as well, but I think its the same kind of mitigation strategy on a different level.

I suggest inspecting the TTL value of the A entry for hub.neurohackademy.org and setting it to 12 hours (43200 seconds).

**Comment by arokem** [comment]
Looks like it [requires issuing a support ticket](https://help.dreamhost.com/hc/en-us/articles/215840248-DNS-propagation-overview ), which I just did.

**Comment by consideRatio** [comment]
Great @arokem! I'll close this issue, we have done what we can at this point I think.
